site:
  $$nodup: true
  name: "weiyu hello site"

  views:
    modules:
      - weiyu.utils.views
      - hello_views

  middlewares:
    pre:
      - session
    post:
      - session

  session:
    # $$include's can be used inside any config dict.
    # Paths are relative to the including file, not to the current working
    # directory.
    $$include: weiyu/session.yml

  staticfile:
    # NOTE: This is relative to the script's working directory.
    root: ./static/

  # Include the Server header in responses.
  # This is disabled by default for security purposes, but here is how to
  # explicitly enable it.
  send_server_header: true


# $$include can also be used in top-level, including whole registries at once.
# This can also be a list!
# Multiple includes will be processed in order.
$$include:
  - weiyu/rendering.yml
  - weiyu/db.yml


# vim:set ai et ts=2 sw=2 sts=2 fenc=utf-8:
