site:
  $$nodup: true

  views:
    modules:
      - weiyu.rendering.views

  scss-bridge:
    # NOTE: This (and other paths) is relative to the entry point script's
    # working directory, unlike include paths.
    root: ./css

weiyu.rendering:
  scss:
    LOAD_PATHS: ./css

    opts:
      # compress defaults to True
      debug_info: true


# vim:set ai et ts=2 sw=2 sts=2 fenc=utf-8:
